### ISSUE TITLE
应该如何部署COGS？

### ISSUE THREAD

**Issue by imcaffrey** [kingfree/cogs#2]
我想给校内OJ部署成COGS

您能指点一下吗？谢谢

**Comment by kingfree** [comment]
可以参考之前的wiki：https://github.com/kingfree/cogs/wiki
并不推荐直接应用本套系统，COGS的本身问题和漏洞很多。
建议有专人维护，不提供技术支持。

**Comment by imcaffrey** [comment]
嗯~谢啦~
